apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: collect-profiles
  namespace: openshift-operator-lifecycle-manager
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    capability.openshift.io/name: "OperatorLifecycleManager"
    include.release.openshift.io/hypershift: "true"
spec:
  podSelector:
    matchLabels:
      app: olm-collect-profiles
  egress:
    - ports:
        - port: 8443
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              name: openshift-operator-lifecycle-manager
        - podSelector:
            matchLabels:
              app: olm-operator
        - podSelector:
            matchLabels:
              app: catalog-operator
    - ports:
        - port: 6443
          protocol: TCP
    - ports:
        - port: dns-tcp
          protocol: TCP
        - port: dns
          protocol: UDP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-dns
  policyTypes:
    - Egress
    - Ingress
